// ReSharper disable InconsistentNaming
namespace Binance
{
    /// <summary>
    /// Defined assets (for convenience/reference only).
    /// </summary>
    public static class Asset
    {
        #region Public Constants

        /// <summary>
        /// Timestamp when the assets were last updated.
        /// </summary>
        public static readonly long LastUpdateAt = 1510122608846;

        public static readonly string ARK = "ARK";
        public static readonly string AST = "AST";
        public static readonly string BCC = "BCC";
        public static readonly string BNB = "BNB";
        public static readonly string BNT = "BNT";
        public static readonly string BQX = "BQX";
        public static readonly string BTC = "BTC";
        public static readonly string BTG = "BTG";
        public static readonly string BTM = "BTM";
        public static readonly string CTR = "CTR";
        public static readonly string DASH = "DASH";
        public static readonly string DNT = "DNT";
        public static readonly string ELC = "ELC";
        public static readonly string ENG = "ENG";
        public static readonly string ENJ = "ENJ";
        public static readonly string EOS = "EOS";
        public static readonly string ETC = "ETC";
        public static readonly string ETH = "ETH";
        public static readonly string EVX = "EVX";
        public static readonly string FUN = "FUN";
        public static readonly string GAS = "GAS";
        public static readonly string HCC = "HCC";
        public static readonly string HSR = "HSR";
        public static readonly string ICN = "ICN";
        public static readonly string IOTA = "IOTA";
        public static readonly string KMD = "KMD";
        public static readonly string KNC = "KNC";
        public static readonly string LINK = "LINK";
        public static readonly string LLT = "LLT";
        public static readonly string LRC = "LRC";
        public static readonly string LTC = "LTC";
        public static readonly string MCO = "MCO";
        public static readonly string MDA = "MDA";
        public static readonly string MOD = "MOD";
        public static readonly string MTH = "MTH";
        public static readonly string MTL = "MTL";
        public static readonly string NEO = "NEO";
        public static readonly string NULS = "NULS";
        public static readonly string OAX = "OAX";
        public static readonly string OMG = "OMG";
        public static readonly string POWR = "POWR";
        public static readonly string QTUM = "QTUM";
        public static readonly string RCN = "RCN";
        public static readonly string REQ = "REQ";
        public static readonly string SALT = "SALT";
        public static readonly string SNGLS = "SNGLS";
        public static readonly string SNM = "SNM";
        public static readonly string SNT = "SNT";
        public static readonly string STORJ = "STORJ";
        public static readonly string STRAT = "STRAT";
        public static readonly string SUB = "SUB";
        public static readonly string TRX = "TRX";
        public static readonly string USDT = "USDT";
        public static readonly string VEN = "VEN";
        public static readonly string VIB = "VIB";
        public static readonly string WTC = "WTC";
        public static readonly string XRP = "XRP";
        public static readonly string XVG = "XVG";
        public static readonly string YOYO = "YOYO";
        public static readonly string ZEC = "ZEC";
        public static readonly string ZRX = "ZRX";

        #endregion Public Constants

        // File generated by BinanceCodeGenerator sample application.
    }
}
