// ReSharper disable InconsistentNaming
namespace Binance
{
    /// <summary>
    /// Defined assets (for convenience/reference only).
    /// </summary>
    public static class Asset
    {
        // <<insert assets>>

        // File generated by BinanceCodeGenerator sample application.
    }
}
