// ReSharper disable InconsistentNaming
namespace Binance
{
    /// <summary>
    /// Defined assets (for convenience/reference only).
    /// </summary>
    public static class Asset
    {
        #region Public Constants

        /// <summary>
        /// Timestamp when the assets were last updated.
        /// </summary>
        // <<insert timestamp>>

        // <<insert assets>>

        #endregion Public Constants

        // File generated by BinanceCodeGenerator sample application.
    }
}
