// ReSharper disable InconsistentNaming
namespace Binance
{
    /// <summary>
    /// Defined symbols (for convienience/reference only).
    /// </summary>
    public static class Symbol
    {
        #region Public Constants

        /// <summary>
        /// When the symbols were last updated.
        /// </summary>
        // <<insert timestamp>>

        // Redirect Bitcoin Cash (BCC = BitConnect)
        public static readonly string BCH_USDT = "BCCUSDT";
        public static readonly string BCH_BTC = "BCCBTC";
        public static readonly string BCH_ETH = "BCCETH";

        // <<insert symbols>>

        #endregion Public Constants

        // File generated by BinanceCodeGenerator tool.
    }
}
