// ReSharper disable InconsistentNaming
namespace Binance
{
    /// <summary>
    /// Defined symbols (for convienience/reference only).
    /// </summary>
    public static class Symbol
    {
        #region Public Constants

        /// <summary>
        /// Timestamp when the symbols were last updated.
        /// </summary>
        // <<insert timestamp>>

        // <<insert symbols>>

        #endregion Public Constants

        // File generated by BinanceCodeGenerator sample application.
    }
}
